-- require("copilot").setup({
--     suggestion = {
--         enabled = true,
--         auto_trigger =true,
--         keymap = {
--             accept = "<Tab>",
--             next = "<C-n>",
--             prev = "<C-p>",
--         }
--     }
-- })
