
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
# size = 8.0 # Office
size = 14.0 # Home

[font.bold]
family = "FiraCode Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono SemBd"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono Light"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 10
y = 5
[env]
term = "xterm-256color"

[general]

live_config_reload = true
import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/themes/tokyo-night.toml"
  # "~/.config/alacritty/themes/rose-pine.yml"
  # "~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]
